name: JARVIS 2

on:
  issue_comment:
    types: [created]

jobs:
  jarvis-brain:
    if: startsWith(github.event.comment.body, '/jarvis')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Run Gemini CLI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extrai o comando do corpo do comentário
          TASK=$(echo "${{ github.event.comment.body }}" | sed 's/^\/jarvis //')
          echo "Executando tarefa: $TASK"
          gemini --allowed-tools run_shell_command "$TASK"