name: Puppeteer Reconnaissance

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install puppeteer cheerio

    - name: Run Puppeteer script
      run: node puppeteer_script.js
      env:
        TARGET_URL: "https://www.xnxx.com/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xnxx-recon-data
        path: ./recon_data/
