name: Run Scraper

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 * * * *' # Runs once every hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Use a compatible Node.js version

    - name: Install dependencies
      run: npm install puppeteer

    - name: Run scraper
      run: |
        ls -l
        node local_scraper.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./scraped_data/
        git commit -m "Scraped data update" || echo "No changes to commit"
        git push
